### ISSUE TITLE
Conv2DSum RuntimeError: Variable -= value not supported

### ISSUE THREAD

**Issue by yannickl96** [pronobis/libspn-keras#25]
Hello again,

I am still trying to get a working example of Conv2DSum up and running. After updating libspn-keras to 0.5.1 the error from #23 disappeared. Now another one is present. See the traceback below:

```
Traceback (most recent call last):
  File "dgcspn_image_classification_extended.py", line 140, in <module>
    spn = def_spn(1000, 64, 3)
  File "dgcspn_image_classification_extended.py", line 121, in def_spn
    spnk.layers.RootSum(return_weighted_child_logits=True)
  File "/home/yannick/miniconda3/envs/dgcspn/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/yannick/miniconda3/envs/dgcspn/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 142, in __init__
    self.add(layer)
  File "/home/yannick/miniconda3/envs/dgcspn/lib/python3.7/site-packages/tensorflow/python/training/tracking/base.py", line 457, in _method_wrapper
    result = method(self, *args, **kwargs)
  File "/home/yannick/miniconda3/envs/dgcspn/lib/python3.7/site-packages/tensorflow/python/keras/engine/sequential.py", line 221, in add
    output_tensor = layer(self.outputs[0])
  File "/home/yannick/miniconda3/envs/dgcspn/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 926, in __call__
    input_list)
  File "/home/yannick/miniconda3/envs/dgcspn/lib/python3.7/site-packages/tensorflow/python/keras/engine/base_layer.py", line 1117, in _functional_construction_call
    outputs = call_fn(cast_inputs, *args, **kwargs)
  File "/home/yannick/miniconda3/envs/dgcspn/lib/python3.7/site-packages/libspn_keras/layers/conv2d_sum.py", line 77, in call
    normalize_in_forward_pass=self._forward_normalize,
  File "/home/yannick/miniconda3/envs/dgcspn/lib/python3.7/site-packages/libspn_keras/sum_ops.py", line 231, in weighted_conv
    return logconv1x1_2d(x, w)
  File "/home/yannick/miniconda3/envs/dgcspn/lib/python3.7/site-packages/libspn_keras/math/logconv.py", line 28, in logconv1x1_2d
    filter -= filter_max
  File "/home/yannick/miniconda3/envs/dgcspn/lib/python3.7/site-packages/tensorflow/python/ops/resource_variable_ops.py", line 1335, in __isub__
    raise RuntimeError("Variable -= value not supported. Use "
RuntimeError: Variable -= value not supported. Use variable.assign_sub(value) to modify the variable value and variable = variable - value to get a new Tensor object.
```

Best,
Yannick

**Comment by jostosh** [comment]
Whoops, I kind of rushed that fix. Won't happen again like this. Found the remaining issues and added tests to prevent these things from slipping into master again. Thanks for reporting! Will be released in a few minutes under version 0.5.2.
