### ISSUE TITLE
No module named 'colorlover'

### ISSUE THREAD

**Issue by anicolson** [pronobis/libspn-keras#8]
Hi Jos, 

Just letting you know about the package that isn't installed during ```pip install libspn-keras```:

````
File "main.py", line 29, in <module>
    from libspn_keras import layers, initializers
  File "/home/aaron/venv/tf2/lib/python3.6/site-packages/libspn_keras/__init__.py", line 14, in <module>
    from libspn_keras.visualize import visualize_dense_spn
  File "/home/aaron/venv/tf2/lib/python3.6/site-packages/libspn_keras/visualize.py", line 8, in <module>
    import colorlover as cl
ModuleNotFoundError: No module named 'colorlover'

````

**Comment by anicolson** [comment]
Also:

```
Traceback (most recent call last):
  File "main.py", line 29, in <module>
    from libspn_keras import layers, initializers
  File "/home/aaron/venv/tf2/lib/python3.6/site-packages/libspn_keras/__init__.py", line 14, in <module>
    from libspn_keras.visualize import visualize_dense_spn
  File "/home/aaron/venv/tf2/lib/python3.6/site-packages/libspn_keras/visualize.py", line 9, in <module>
    import plotly.graph_objects as go
ModuleNotFoundError: No module named 'plotly'

```

**Comment by jostosh** [comment]
Should be fixed with the latest version on `pypi`
