### ISSUE TITLE
Issue saving RAT-SPN

### ISSUE THREAD

**Issue by anicolson** [pronobis/libspn-keras#9]
Hi Jos, 

I am using a RAT-SPN identical to the one in your colab tutorial: https://colab.research.google.com/drive/1uvJd1Q6wUdEkM2dpT4wkZfNT6lgj-2u3

One of the ```libpsn_keras.layers``` seems to not have a ```get_config```  setup, not allowing the model to be saved.

Both ``` Undecompose``` and ``` PermuteAndPadScopes ``` both do not have a ```get_config``` which is probably causing the error

````

Traceback (most recent call last):
  File "main.py", line 146, in <module>
    model.compile(opt, args.model_path)
  File "/scratch/s2842809/home/Thoth/thoth/ctc_model.py", line 76, in compile
    with open(save_dir + "/model.json", "w") as json_file: json_file.write(self.model.to_json())
  File "/export/home/s2842809/scratch/home/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1254, in to_json
    model_config = self._updated_config()
  File "/export/home/s2842809/scratch/home/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1232, in _updated_config
    config = self.get_config()
  File "/export/home/s2842809/scratch/home/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 918, in get_config
    return copy.deepcopy(get_network_config(self))
  File "/export/home/s2842809/scratch/home/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/network.py", line 1993, in get_network_config
    layer_config = serialize_layer_fn(layer)
  File "/export/home/s2842809/scratch/home/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 198, in serialize_keras_object
    config = instance.get_config()
  File "/export/home/s2842809/scratch/home/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/layers/wrappers.py", line 76, in get_config
    'config': self.layer.get_config()
  File "/export/home/s2842809/scratch/home/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/sequential.py", line 347, in get_config
    layer_configs.append(generic_utils.serialize_keras_object(layer))
  File "/export/home/s2842809/scratch/home/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/utils/generic_utils.py", line 198, in serialize_keras_object
    config = instance.get_config()
  File "/export/home/s2842809/scratch/home/miniconda3/envs/tf2/lib/python3.7/site-packages/tensorflow_core/python/keras/engine/base_layer.py", line 499, in get_config
    raise NotImplementedError('Layers with arguments in `__init__` must '
NotImplementedError: Layers with arguments in `__init__` must override `get_config`.

````

**Comment by jostosh** [comment]
Thanks for pointing that out! Should be easy to fix. Feel free to also create a PR

**Comment by jostosh** [comment]
I won't have the chance to do that until tomorrow

**Comment by jostosh** [comment]
Should be fixed with the latest version on `pypi`
